### ISSUE TITLE
How can I implement this concepts with react project?

### ISSUE THREAD

**Issue by EdisonDevadoss** [VirgilSecurity/demo-firebase-func#3]
Virgil security with react native....

**Comment by xlwknx** [comment]
This is a backend repository.
I don't know what `concepts`you mean, but we have client library that support react native:
https://github.com/VirgilSecurity/virgil-e3kit-js#react-native-usage
It is using this as backend:
https://github.com/VirgilSecurity/virgil-e3kit-firebase-func
You can find implementation guide here:
https://dashboard.virgilsecurity.com/guide/firebase
And we have demo with react (not native):
https://github.com/VirgilSecurity/demo-firebase-js

I'm closing this issue, if you have a question we have slack community:
